services:
  # FastAPI Backend Service
  - type: web
    name: mcd-scraper-api
    env: python
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && python -m uvicorn main:app --host 0.0.0.0 --port $PORT"
    rootDir: .
    plan: starter
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: TURSO_DATABASE_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false
      - key: GEOCODING_PROVIDER
        value: "nominatim"
      - key: GEMINI_API_KEY
        sync: false
      - key: CHATBOT_PROVIDER
        value: "gemini"
      - key: DEBUG
        value: "false"
      - key: LOG_LEVEL
        value: "info"

  # Next.js Frontend Service
  - type: web
    name: mcd-scraper-frontend
    env: node
    buildCommand: "cd frontend && npm install && npm run build"
    startCommand: "cd frontend && npm start"
    rootDir: .
    plan: starter
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: "https://mcd-scraper-api.onrender.com"
      - key: NEXT_PUBLIC_MAP_PROVIDER
        value: "react-leaflet"
      - key: NEXT_PUBLIC_MAP_TILES
        value: "openstreetmap" 